/* Generated by            cobc 1.1.0 */
/* Generated from          ./src/a.cob */
/* Generated at            Apr 15 2020 01:26:30 DST */
/* OpenCOBOL build date    Aug 04 2016 15:56:22 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -free -x -C -o ./src/a.c ./src/a.cob */


/* Define perform frame stack */

struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];

