/* Generated by            cobc 1.1.0 */
/* Generated from          ./src/a.cob */
/* Generated at            Apr 15 2020 01:26:30 DST */
/* OpenCOBOL build date    Aug 04 2016 15:56:22 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -free -x -C -o ./src/a.c ./src/a.cob */

/* Frame stack declaration */
struct cob_frame {
	int	perform_through;
	void	*return_address;
};

/* Union for CALL statement */
union cob_call_union {
	void *(*funcptr)();
	int  (*funcint)();
	void *func_void;
};
union cob_call_union	cob_unifunc;


/* Storage */

/* PROGRAM-ID : HELLO */
static unsigned char b_1[4] __attribute__((aligned));	/* RETURN-CODE */

/* End of storage */


/* Attributes */

static const cob_field_attr a_1 = {33, 0, 0, 0, NULL};
/* Constants */
static cob_field c_1	= {11, (unsigned char *)"Hello World", &a_1};

